from os.path import join, dirname, abspath


OBJECTIFY_BASE_FOLDER = dirname(dirname(abspath(__file__)))
MODEL_WEIGHTS_FOLDER = join(OBJECTIFY_BASE_FOLDER, "model_weights")
POINTREND_MODEL_PATH = join(MODEL_WEIGHTS_FOLDER, "pointrend_resnet50.pkl")
print(POINTREND_MODEL_PATH)
MANTHAN21_ROOT_FOLDER = dirname(OBJECTIFY_BASE_FOLDER)
WEBAPP_FOLDER = join(MANTHAN21_ROOT_FOLDER, "WebApp")
MEDIA_FOLDER = join(WEBAPP_FOLDER, "media")
STATIC_FOLDER = join(MEDIA_FOLDER, "static")
DEMONSTRATION_JSON_PATH = join(STATIC_FOLDER, "demo.json")
IMAGES_FOLDER = join(STATIC_FOLDER, "images")
OUTPUT_IMAGE_STATIC_PATH = join(IMAGES_FOLDER, "out.png")
OUTPUT_IMAGE_MEDIA_FOLDER = join(MEDIA_FOLDER, "images")
OUTPUT_IMAGE_MEDIA_PATH = join(OUTPUT_IMAGE_MEDIA_FOLDER, "out.png")
