# Generated by Django 3.2.4 on 2021-10-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_savemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savemodel',
            old_name='content',
            new_name='task',
        ),
        migrations.AddField(
            model_name='savemodel',
            name='modeltype',
            field=models.TextField(default=''),
        ),
    ]
