# Generated by Django 3.2.4 on 2021-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20211029_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='savemodel',
            name='choices',
            field=models.TextField(default=''),
        ),
    ]
